config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :orders
  resources :order_items
  resources :products
  root to: "products#index"
 # get '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/:provider/callback', to: 'sessions#create', via: :get
  match '/login'=> redirect("/auth/twitter"), as: :login, via: :get
  match '/logout' => "sessions#destroy", as: :logout, via: :get
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodWorks - Products: <%= controller.action_name %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="wrapper">
  		<div class="header">
  			<h1><%= link_to("FoodWorks", products_path) %></h1>
  			<p>Your Online Grocery</p>
  		</div>
  		<p style="color: green"><%= flash[:notice]  %></p>
	<div id="account">
		<% if current_user %>
			<span>Welcome, <%= current_user.name %></span>
			<%=link_to "logout", logout_path, id: "login" %>
		<% else %>
		<%= link_to "login", login_path, id: "logout" %>  	
	<% end %>		
	</div>
  		<div class="sidebar">
  			(sidebar)
  		</div>

  		<div class="main">
		    <%= yield %>
  		</div>

  		<div class="footer">
  			FoodWorks Online Grocery<br/>
  			A Rails Project
  		</div>
  	
  </div>
  </body>
</html>